import { serializeViewSpec, specDatumKey, specScopes } from '../spec-meta.js';
import { compileLineage } from '../data/lineage.js';
import { validateTransforms } from '../data/validate.js';
import { normalizeFilter } from '../data/filter.js';
import { validateCanonicalPositionDomains } from './declaration-domains.js';
import type {
  CanonicalDeclarationOperation,
  DeclarationCodecResult,
  DeclarationOperationCodec,
  ViewSpec
} from '../types/index.js';

const forbiddenPathSegments = new Set(['__proto__', 'constructor', 'prototype']);
const protectedRoots = new Set(['data', 'datumKey']);

export interface DeclarationOperationCodecOptions<S extends ViewSpec> {
  /** Whole semantic slots which may update several serialized leaves at once. */
  atomicPaths?: readonly (readonly string[])[];
  /** Known top-level declaration fields. Unknown fields are explicitly unsupported. */
  allowedRoots?: readonly string[];
  /** Derived paths excluded from operations and regenerated by normalize(). */
  derivedPaths?: readonly (readonly string[])[];
  normalize?: (spec: S) => S;
  validate?: (spec: S) => string | void;
  /** Extra stable sequence paths; transforms are always a supported sequence. */
  sequences?: readonly { id: string; path: readonly string[] }[];
}

export interface StandardDeclarationCodecOptions<S extends ViewSpec> {
  mark: string;
  requiredChannels?: readonly string[];
  allowedChannels?: readonly string[];
  allowedRoots?: readonly string[];
  atomicPaths?: readonly (readonly string[])[];
  validate?: (spec: S) => string | void;
}

const standardDeclarationRoots = ['mark', 'data', 'encoding', 'transform', 'key', 'datumKey', 'margin', 'meta'];
const standardEncodingChannels = ['x', 'y', 'color', 'size', 'detail', 'tooltip', 'key', 'xOffset', 'yOffset'];

/** Shared conservative codec for chart peers with ordinary field/channel state. */
export function createStandardDeclarationOperationCodec<S extends ViewSpec>(
  options: StandardDeclarationCodecOptions<S>
): DeclarationOperationCodec<S> {
  return createDeclarationOperationCodec<S>({
    allowedRoots: options.allowedRoots ?? standardDeclarationRoots,
    atomicPaths: [['margin'], ...(options.atomicPaths ?? [])],
    validate: spec => validateStandardDeclaration(spec, options)
  });
}

/** Validate complete ordinary channels and common endpoint requirements. */
export function validateCanonicalEncoding(
  spec: ViewSpec,
  allowedChannels: readonly string[] = standardEncodingChannels
): string | null {
  const allowedTypes = new Set(['quantitative', 'temporal', 'nominal', 'ordinal']);
  const allowed = new Set(allowedChannels);
  for (const [channel, raw] of Object.entries(spec.encoding ?? {})) {
    if (!allowed.has(channel)) return `unsupported encoding channel: ${channel}`;
    for (const value of Array.isArray(raw) ? raw : [raw]) {
      if (!value || typeof value !== 'object' || Array.isArray(value)) return `${channel} encoding must be a channel declaration`;
      const declaration = value as Record<string, unknown>;
      const hasField = Object.prototype.hasOwnProperty.call(declaration, 'field');
      const hasValue = Object.prototype.hasOwnProperty.call(declaration, 'value');
      if (hasField === hasValue) return `${channel} encoding must declare exactly one of field or value`;
      if (hasField && (typeof declaration.field !== 'string' || declaration.field.length === 0)) return `${channel} field must be a non-empty string`;
      if (channel === 'color' && hasValue && typeof declaration.value !== 'string') return 'constant color values must be strings';
      if (declaration.type !== undefined && (typeof declaration.type !== 'string' || !allowedTypes.has(declaration.type))) return `${channel} encoding has an unsupported data type`;
      if (declaration.aggregate !== undefined || declaration.bin !== undefined || declaration.timeUnit !== undefined) {
        return `${channel} grain parameters require a chart-authored route`;
      }
    }
  }
  return null;
}

function validateStandardDeclaration<S extends ViewSpec>(
  spec: S,
  options: StandardDeclarationCodecOptions<S>
): string | void {
  if (spec.mark !== options.mark) return `declaration is not a ${options.mark}`;
  const transformError = validateCanonicalTransformPipeline(spec);
  if (transformError) return transformError;
  const encodingError = validateCanonicalEncoding(spec, options.allowedChannels);
  if (encodingError) return encodingError;
  const domainError = validateCanonicalPositionDomains(spec);
  if (domainError) return domainError;
  for (const channel of options.requiredChannels ?? []) {
    const value = spec.encoding?.[channel];
    const first = Array.isArray(value) ? value[0] : value;
    if (!first || typeof first !== 'object' || typeof first.field !== 'string' || !first.field) {
      return `${options.mark} declarations require a field binding for ${channel}`;
    }
  }
  const serialized = serializeViewSpec(spec);
  const meta = serialized.meta;
  if (meta && Object.keys(meta).some(key => !['object', 'lineage', 'state'].includes(key))) return 'metadata is outside the canonical declaration subset';
  if (meta?.object && Object.keys(meta.object).some(key => key !== 'key')) return 'object metadata is outside the canonical declaration subset';
  if (meta?.lineage && Object.keys(meta.lineage).some(key => key !== 'key')) return 'lineage metadata is outside the canonical declaration subset';
  if (meta?.state && Object.keys(meta.state).some(key => key !== 'scopes')) return 'chart state metadata is outside the canonical declaration subset';
  if (meta?.state?.scopes && Object.keys(meta.state.scopes).some(key => key !== 'focus' && key !== 'highlight')) return 'only focus and highlight scopes are canonical operations';
  const attentionError = validateCanonicalAttentionScopes(spec);
  if (attentionError) return attentionError;
  const missingField = validateCanonicalDataFields(spec);
  if (missingField) return `declaration references unknown inline-data field "${missingField}"`;
  const datumIdentityError = validateExplicitSourceDatumIdentity(spec);
  if (datumIdentityError) return datumIdentityError;
  return options.validate?.(spec);
}

export function validateCanonicalDataFields(spec: ViewSpec): string | null {
  const rawData = spec.data;
  const rows = Array.isArray(rawData)
    ? rawData
    : rawData && typeof rawData === 'object' && Array.isArray((rawData as Record<string, unknown>)['values'])
      ? (rawData as { values: unknown[] }).values
      : null;
  if (!rows) return null;
  if (!rows.every(row => row && typeof row === 'object' && !Array.isArray(row))) return 'data.values';
  const fields = new Set(rows.flatMap(row => Object.keys(row as Record<string, unknown>)));
  for (const transform of spec.transform ?? []) {
    if (Object.prototype.hasOwnProperty.call(transform, 'timeUnit')) {
      const item = (transform as { timeUnit: { field: string; unit: string; as?: string } }).timeUnit;
      if (!fields.has(item.field)) return item.field;
      fields.add(item.as ?? `${item.field}_${item.unit}`);
    } else if (Object.prototype.hasOwnProperty.call(transform, 'filter')) {
      const item = (transform as { filter: { field: string } }).filter;
      if (!fields.has(item.field)) return item.field;
    } else if (Object.prototype.hasOwnProperty.call(transform, 'sort')) {
      const item = (transform as { sort: { field?: string; fields?: Array<string | { field: string }> } }).sort;
      if (item.field && !fields.has(item.field)) return item.field;
      for (const entry of item.fields ?? []) {
        const field = typeof entry === 'string' ? entry : entry.field;
        if (!fields.has(field)) return field;
      }
    }
  }
  for (const value of Object.values(spec.encoding ?? {})) {
    for (const channel of Array.isArray(value) ? value : [value]) {
      if (channel?.field && !fields.has(channel.field)) return channel.field;
    }
  }
  const objectKey = serializeViewSpec(spec).meta?.object?.key;
  for (const field of Array.isArray(objectKey) ? objectKey : [objectKey]) {
    if (typeof field === 'string' && !fields.has(field)) return field;
  }
  const scopes = specScopes(spec);
  for (const scope of [scopes.focus, scopes.highlight]) {
    const selection = scope as Record<string, unknown> | null | undefined;
    const filters = selection?.filters ?? (selection?.filter ? [selection.filter] : []);
    for (const raw of filters as unknown[]) {
      const filter = normalizeFilter(raw);
      if (!fields.has(filter.field)) return filter.field;
    }
  }
  return null;
}

/** Verify explicit source-record identity against the complete inline source. */
export function validateExplicitSourceDatumIdentity(spec: ViewSpec): string | null {
  const key = specDatumKey(spec);
  if (key == null) return null;
  const data = serializeViewSpec(spec).data;
  const rows = Array.isArray(data)
    ? data
    : data && typeof data === 'object' && Array.isArray((data as Record<string, unknown>)['values'])
      ? (data as { values: unknown[] }).values
      : null;
  if (!rows) return 'cannot verify explicit datum identity without resolved inline source rows';
  if (!rows.every(row => row && typeof row === 'object' && !Array.isArray(row))) {
    return 'explicit datum identity requires inline source rows to be records';
  }

  const fields = new Set(rows.flatMap(row => Object.keys(row as Record<string, unknown>)));
  const keyFields = Array.isArray(key) ? key : [key];
  for (const field of keyFields) {
    if (!fields.has(field)) return `datumKey references unknown inline-data field "${field}"`;
  }

  try {
    // Use the lineage implementation's key encoder and duplicate semantics.
    compileLineage(rows as import('../types/index.js').DataRow[], [], { key });
  } catch (error) {
    return error instanceof Error ? error.message : 'explicit datum identity is invalid';
  }
  return null;
}

/** Validate the existing transform contract and exclude grain-changing operations. */
export function validateCanonicalTransformPipeline(spec: ViewSpec): string | null {
  try { validateTransforms(spec.transform ?? []); }
  catch (error) { return error instanceof Error ? error.message : 'invalid transform declaration'; }
  return supportsCanonicalTransforms(spec) ? null : 'aggregate or unknown transforms require a chart-authored route';
}

/** Validate attention scopes using the same filter normalizer as rendering. */
export function validateCanonicalAttentionScopes(spec: ViewSpec): string | null {
  const scopes = specScopes(spec);
  for (const [key, scope] of [['focus', scopes?.focus], ['highlight', scopes?.highlight]] as const) {
    if (scope == null) continue;
    if (typeof scope !== 'object' || Array.isArray(scope)) return `${key} scope must be an object`;
    const selection = scope as Record<string, unknown>;
    if (Object.keys(selection).some(name => !['mode', 'filter', 'filters', 'opacity', 'field', 'equal'].includes(name))) {
      return `${key} scope has unsupported properties`;
    }
    if (selection.mode !== key) return `${key} scope mode must be ${key}`;
    if (selection.opacity !== undefined && (typeof selection.opacity !== 'number' || !Number.isFinite(selection.opacity) || selection.opacity < 0 || selection.opacity > 1)) {
      return `${key} scope opacity must be between 0 and 1`;
    }
    if (selection.filter !== undefined) {
      try { normalizeFilter(selection.filter); }
      catch (error) { return `${key} scope: ${error instanceof Error ? error.message : 'invalid filter'}`; }
    }
    if (selection.filters !== undefined) {
      if (!Array.isArray(selection.filters) || selection.filters.length === 0) return `${key} scope filters must be a non-empty array`;
      for (const filter of selection.filters) {
        try { normalizeFilter(filter); }
        catch (error) { return `${key} scope: ${error instanceof Error ? error.message : 'invalid filter'}`; }
      }
    }
    if (selection.filter === undefined && selection.filters === undefined && typeof selection.field === 'string') {
      try { normalizeFilter({ field: selection.field, equal: selection.equal }); }
      catch (error) { return `${key} scope: ${error instanceof Error ? error.message : 'invalid filter'}`; }
    }
    if (selection.filter === undefined && selection.filters === undefined && typeof selection.field !== 'string') {
      return `${key} scope requires a filter`;
    }
  }
  return null;
}

/** A structured codec for explicitly supported declaration families. */
export function createDeclarationOperationCodec<S extends ViewSpec>(
  options: DeclarationOperationCodecOptions<S> = {}
): DeclarationOperationCodec<S> {
  const atomicPaths = new Set((options.atomicPaths ?? []).map(pathKey));
  const derivedPaths = new Set((options.derivedPaths ?? []).map(pathKey));
  const allowedRoots = options.allowedRoots ? new Set(options.allowedRoots) : null;
  const sequences = [{ id: 'transform', path: ['transform'] }, ...(options.sequences ?? [])];

  const fail = <T>(reason: string): DeclarationCodecResult<T> => ({ status: 'unsupported', reason });
  const ok = <T>(value: T): DeclarationCodecResult<T> => ({ status: 'ok', value });

  const codec: DeclarationOperationCodec<S> = {
    decompose(spec) {
      const inputError = validateSupportedValue(spec, true);
      if (inputError) return fail(inputError);
      if (allowedRoots) {
        const unknown = Object.keys(spec as Record<string, unknown>).find(key => !allowedRoots.has(key));
        if (unknown) return fail(`unsupported declaration field: ${unknown}`);
      }
      const reason = options.validate?.(spec);
      if (typeof reason === 'string') return fail(reason);
      let serialized: Record<string, unknown>;
      try { serialized = serializeViewSpec(spec) as Record<string, unknown>; }
      catch (error) { return fail(errorMessage(error, 'declaration serialization failed')); }
      preserveUndefined(spec as Record<string, unknown>, serialized);

      const operations: CanonicalDeclarationOperation[] = [];
      for (const sequence of sequences) {
        const value = getPath(serialized, [...sequence.path]);
        if (!value.present) continue;
        if (!Array.isArray(value.value)) return fail(`ordered sequence ${sequence.id} must be an array`);
        const occurrences = new Map<string, number>();
        for (const item of value.value) {
          const valueKey = stableValueKey(item);
          if (valueKey.status !== 'ok') return fail(valueKey.reason);
          const duplicate = occurrences.get(valueKey.value) ?? 0;
          occurrences.set(valueKey.value, duplicate + 1);
          operations.push({
            id: `${sequence.id}:${valueKey.value}:${duplicate}`,
            path: [...sequence.path],
            sequence: sequence.id,
            value: { present: true, value: clone(item) }
          });
        }
      }

      const sequenceRoots = sequences.map(sequence => pathKey(sequence.path));
      for (const key of Object.keys(serialized).sort()) {
        if (protectedRoots.has(key) || !record(serialized[key])) {
          if (protectedRoots.has(key) || sequences.some(sequence => sequence.path.length === 1 && sequence.path[0] === key)) continue;
          if (derivedPaths.has(key)) continue;
          if (serialized[key] === undefined) {
            operations.push({ id: key, path: [key], value: { present: true, value: undefined } });
          } else if (!record(serialized[key])) {
            operations.push({ id: key, path: [key], value: { present: true, value: clone(serialized[key]) } });
          }
          continue;
        }
        if (sequenceRoots.includes(key)) continue;
        if (derivedPaths.has(key)) continue;
        const nested = visit(serialized[key], [key]);
        if (nested.status !== 'ok') return nested;
      }
      operations.sort((a, b) => {
        if (a.sequence && b.sequence && a.sequence === b.sequence) return 0;
        if (a.sequence) return 1;
        if (b.sequence) return -1;
        return a.id.localeCompare(b.id);
      });
      return ok(operations);

      function visit(value: unknown, path: string[]): DeclarationCodecResult<void> {
        const key = pathKey(path);
        if (unsafePath(path)) return fail(`unsafe declaration path: ${path.join('.')}`);
        if (derivedPaths.has(key)) return ok(undefined);
        if (atomicPaths.has(key) || isChannelSlot(path) || isAttentionScope(path)) {
          operations.push({ id: key, path, value: { present: true, value: clone(value) } });
          return ok(undefined);
        }
        if (record(value) && Object.keys(value).length) {
          for (const childKey of Object.keys(value).sort()) {
            if (forbiddenPathSegments.has(childKey)) return fail(`unsafe declaration path: ${[...path, childKey].join('.')}`);
            const child = visit(value[childKey], [...path, childKey]);
            if (child.status !== 'ok') return child;
          }
          return ok(undefined);
        }
        operations.push({ id: key, path, value: { present: true, value: clone(value) } });
        return ok(undefined);
      }
    },
    evaluate(template, inputOperations) {
      const operationError = validateOperations(inputOperations);
      if (operationError) return fail(operationError);
      let result: Record<string, unknown>;
      try { result = serializeViewSpec(template) as Record<string, unknown>; }
      catch (error) { return fail(errorMessage(error, 'declaration serialization failed')); }
      const sourceOps = codec.decompose(template);
      if (sourceOps.status !== 'ok') return sourceOps;
      for (const operation of sourceOps.value) {
        if (operation.sequence) {
          deletePath(result, operation.path);
          continue;
        }
        deletePath(result, operation.path);
      }
      for (const sequence of sequences) deletePath(result, [...sequence.path]);
      for (const derivedPath of derivedPaths) deletePath(result, derivedPath.split('/'));

      const sequenceValues = new Map<string, unknown[]>();
      for (const operation of inputOperations) {
        if (!operation.value.present) continue;
        if (operation.sequence) {
          const values = sequenceValues.get(operation.sequence) ?? [];
          values.push(clone(operation.value.value));
          sequenceValues.set(operation.sequence, values);
        } else {
          const error = setPath(result, operation.path, clone(operation.value.value));
          if (error) return fail(error);
        }
      }
      for (const sequence of sequences) {
        const values = sequenceValues.get(sequence.id);
        if (values?.length) {
          const error = setPath(result, [...sequence.path], values);
          if (error) return fail(error);
        }
      }
      let candidate = result as S;
      try { candidate = canonicalizeDeclaration(options.normalize ? options.normalize(candidate) : candidate); }
      catch (error) { return fail(errorMessage(error, 'declaration evaluation failed')); }
      const validation = codec.validate(candidate);
      if (validation.status !== 'ok') return validation;
      const roundTrip = codec.decompose(candidate);
      if (roundTrip.status !== 'ok') return roundTrip;
      if (!sameOperationLists(roundTrip.value, inputOperations)) {
        return fail('operation evaluation does not round-trip to the same canonical operations');
      }
      return ok(candidate);
    },
    normalize(spec) {
      const inputError = validateSupportedValue(spec, true);
      if (inputError) return fail(inputError);
      if (allowedRoots) {
        const unknown = Object.keys(spec as Record<string, unknown>).find(key => !allowedRoots.has(key));
        if (unknown) return fail(`unsupported declaration field: ${unknown}`);
      }
      let normalized = spec;
      try { normalized = canonicalizeDeclaration(options.normalize ? options.normalize(spec) : spec); }
      catch (error) { return fail(errorMessage(error, 'declaration normalization failed')); }
      const validation = codec.validate(normalized);
      return validation.status === 'ok' ? ok(normalized) : validation;
    },
    validate(spec) {
      const inputError = validateSupportedValue(spec, true);
      if (inputError) return fail(inputError);
      if (allowedRoots) {
        const unknown = Object.keys(spec as Record<string, unknown>).find(key => !allowedRoots.has(key));
        if (unknown) return fail(`unsupported declaration field: ${unknown}`);
      }
      let serialized: Record<string, unknown>;
      try { serialized = serializeViewSpec(spec) as Record<string, unknown>; }
      catch (error) { return fail(errorMessage(error, 'declaration serialization failed')); }
      const pathError = validatePathKeys(serialized, []);
      if (pathError) return fail(pathError);
      const reason = options.validate?.(spec);
      return typeof reason === 'string' ? fail(reason) : ok(undefined);
    }
  };
  return codec;

  function canonicalizeDeclaration(value: S): S {
    const canonical = serializeViewSpec(value) as S;
    preserveUndefined(value as Record<string, unknown>, canonical as Record<string, unknown>);
    return canonical;
  }
}

/** Source data and datum identity are route boundaries; mark keys may change with grain. */
export function sameProtectedDeclarations(a: ViewSpec, b: ViewSpec): boolean {
  try {
    const left = serializeViewSpec(a);
    const right = serializeViewSpec(b);
    return deepEqualOpaqueData(left.data, right.data) && deepEqual(specDatumKey(left), specDatumKey(right));
  } catch {
    return false;
  }
}

/** Aggregate transforms stay coupled to chart-owned grain metadata. */
export function supportsCanonicalTransforms(spec: ViewSpec): boolean {
  return (spec.transform ?? []).every(transform => {
    if (!record(transform)) return false;
    const keys = Object.keys(transform);
    return keys.length === 1 && ['filter', 'sort', 'timeUnit'].includes(keys[0]!);
  });
}

export function stableValueKey(value: unknown): DeclarationCodecResult<string> {
  const error = validateSupportedValue(value, false);
  if (error) return { status: 'unsupported', reason: error };
  return { status: 'ok', value: encodeStable(value) };
}

export function deepEqual(a: unknown, b: unknown): boolean {
  const left = stableValueKey(a);
  const right = stableValueKey(b);
  return left.status === 'ok' && right.status === 'ok' && left.value === right.value;
}

function isChannelSlot(path: string[]): boolean {
  return path[0] === 'encoding' && path.length === 2;
}

function isAttentionScope(path: string[]): boolean {
  return path[0] === 'meta' && path[1] === 'state' && path[2] === 'scopes' &&
    (path[3] === 'focus' || path[3] === 'highlight') && path.length === 4;
}

function getPath(root: Record<string, unknown>, path: string[]): { present: boolean; value?: unknown } {
  let value: unknown = root;
  for (const segment of path) {
    if (!record(value) || !Object.prototype.hasOwnProperty.call(value, segment)) return { present: false };
    value = value[segment];
  }
  return { present: true, value };
}

function setPath(root: Record<string, unknown>, path: string[], value: unknown): string | null {
  if (!path.length || unsafePath(path)) return `unsafe declaration path: ${path.join('.')}`;
  let parent = root;
  for (const segment of path.slice(0, -1)) {
    if (!Object.prototype.hasOwnProperty.call(parent, segment)) parent[segment] = {};
    if (!record(parent[segment])) return `invalid declaration parent: ${path.join('.')}`;
    parent = parent[segment] as Record<string, unknown>;
  }
  parent[path[path.length - 1]!] = value;
  return null;
}

function deletePath(root: Record<string, unknown>, path: string[]): void {
  if (!path.length || unsafePath(path)) return;
  let parent = root;
  for (const segment of path.slice(0, -1)) {
    if (!record(parent[segment])) return;
    parent = parent[segment] as Record<string, unknown>;
  }
  delete parent[path[path.length - 1]!];
}

function validateOperations(operations: readonly CanonicalDeclarationOperation[]): string | null {
  const ids = new Set<string>();
  for (const operation of operations) {
    if (!operation.id || ids.has(operation.id)) return `duplicate or empty canonical operation ID: ${operation.id}`;
    ids.add(operation.id);
    if (unsafePath(operation.path)) return `unsafe declaration path: ${operation.path.join('.')}`;
    if (!operation.value.present) return 'canonical endpoint operations must carry a present value';
    const error = validateSupportedValue(operation.value.value, false);
    if (error) return error;
  }
  return null;
}

function validatePathKeys(value: unknown, path: string[]): string | null {
  // Data is an opaque JSON payload. Keys inside records are user data, not
  // declaration paths that the evaluator will ever traverse.
  if (path.length === 0 && record(value) && Object.prototype.hasOwnProperty.call(value, 'data')) {
    const { data: _opaqueData, ...declaration } = value;
    return validatePathKeys(declaration, []);
  }
  if (Array.isArray(value)) {
    for (const [index, item] of value.entries()) {
      const error = validatePathKeys(item, [...path, String(index)]);
      if (error) return error;
    }
  } else if (record(value)) {
    for (const [key, child] of Object.entries(value)) {
      const next = [...path, key];
      if (unsafePath(next)) return `unsafe declaration path: ${next.join('.')}`;
      const error = validatePathKeys(child, next);
      if (error) return error;
    }
  }
  return null;
}

function preserveUndefined(source: Record<string, unknown>, target: Record<string, unknown>): void {
  for (const key of Object.keys(source)) {
    if (source[key] === undefined && !Object.prototype.hasOwnProperty.call(target, key)) {
      target[key] = undefined;
    } else if (record(source[key]) && record(target[key])) {
      preserveUndefined(source[key] as Record<string, unknown>, target[key] as Record<string, unknown>);
    }
  }
}

function validateSupportedValue(value: unknown, ignoreDataRoot: boolean, allowUnsafeDataKeys = false): string | null {
  const active = new WeakSet<object>();
  const visit = (entry: unknown, path: string[], opaqueData = false): string | null => {
    if (entry === null || entry === undefined || typeof entry === 'string' || typeof entry === 'boolean') return null;
    if (typeof entry === 'number') return Number.isFinite(entry) ? null : `unsupported non-finite number at ${path.join('.') || '<value>'}`;
    if (typeof entry === 'function' || typeof entry === 'symbol' || typeof entry === 'bigint') return `unsupported ${typeof entry} value at ${path.join('.') || '<value>'}`;
    if (entry instanceof Date) return Number.isFinite(entry.getTime()) ? null : `invalid Date at ${path.join('.') || '<value>'}`;
    if (Array.isArray(entry)) {
      if (active.has(entry)) return `unsupported circular value at ${path.join('.') || '<value>'}`;
      active.add(entry);
      for (let index = 0; index < entry.length; index++) {
        const error = visit(entry[index], [...path, String(index)], opaqueData);
        if (error) { active.delete(entry); return error; }
      }
      active.delete(entry);
      return null;
    }
    if (record(entry)) {
      if (active.has(entry)) return `unsupported circular value at ${path.join('.') || '<value>'}`;
      active.add(entry);
      if (Object.getOwnPropertySymbols(entry).length) return `unsupported symbol key at ${path.join('.') || '<value>'}`;
      for (const key of Object.keys(entry)) {
        const next = [...path, key];
        const childInData = opaqueData || (ignoreDataRoot && path.length === 0 && key === 'data');
        if (!childInData && !allowUnsafeDataKeys && forbiddenPathSegments.has(key)) { active.delete(entry); return `unsafe declaration path: ${next.join('.')}`; }
        const error = visit(entry[key], next, childInData);
        if (error) { active.delete(entry); return error; }
      }
      active.delete(entry);
      return null;
    }
    return `unsupported value at ${path.join('.') || '<value>'}`;
  };
  return visit(value, []);
}

function deepEqualOpaqueData(a: unknown, b: unknown): boolean {
  const leftError = validateSupportedValue(a, false, true);
  const rightError = validateSupportedValue(b, false, true);
  return !leftError && !rightError && encodeStable(a) === encodeStable(b);
}

function unsafePath(path: readonly string[]): boolean {
  return path.some(segment => forbiddenPathSegments.has(segment));
}

function pathKey(path: readonly string[]): string { return path.join('/'); }

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) && !(value instanceof Date);
}

function clone<T>(value: T): T {
  if (Array.isArray(value)) return value.map(clone) as T;
  if (record(value)) return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, clone(item)])) as T;
  if (value instanceof Date) return new Date(value.getTime()) as T;
  return value;
}

function encodeStable(value: unknown): string {
  if (value === undefined) return 'u';
  if (value === null) return 'n';
  if (typeof value === 'string') return `s${value.length}:${value}`;
  if (typeof value === 'boolean') return value ? 'b1' : 'b0';
  if (typeof value === 'number') return `d${String(value)}`;
  if (value instanceof Date) return `t${value.getTime()}`;
  if (Array.isArray(value)) return `a[${value.map(encodeStable).join(',')}]`;
  if (record(value)) return `o{${Object.keys(value).sort().map(key => `${encodeStable(key)}:${encodeStable(value[key])}`).join(',')}}`;
  return 'unsupported';
}

function sameOperationLists(a: readonly CanonicalDeclarationOperation[], b: readonly CanonicalDeclarationOperation[]): boolean {
  return a.length === b.length && a.every((operation, index) => {
    const other = b[index];
    return operation.sequence === other?.sequence && (operation.sequence ? true : operation.id === other?.id) &&
      operation.path.length === other.path.length && operation.path.every((segment, i) => segment === other.path[i]) &&
      operation.value.present === other.value.present &&
      (!operation.value.present || (other.value.present && deepEqual(operation.value.value, other.value.value)));
  });
}

function errorMessage(error: unknown, fallback: string): string {
  return error instanceof Error ? error.message : fallback;
}
